version: '3'
services:
  odoo:
    image: phyopyae/odoo_16_based_docker
    env_file: .env
    depends_on:
      - postgres
    network_mode: host
    volumes:
      - data:/var/lib/odoo
  postgres:
    image: phyopyae/odoo_16_based_postgres_docker
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
